### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by lehuygiang28** [hoalongnatsu/Dockerfile#2]
Thank you for sharing your project! Could you please add a license to the repository? This will clarify what I can do with it after forking. See [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) and [here](https://choosealicense.com/) for more information.

**Comment by lehuygiang28** [comment]
Hey @hoalongnatsu, can you check this

**Comment by hoalongnatsu** [comment]
ok, let's me see, thank you

**Comment by hoalongnatsu** [comment]
I added a license, thank you
